//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrencyCounter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CurrencyCounter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bills.
        /// </summary>
        public static string billsLbl {
            get {
                return ResourceManager.GetString("billsLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coins.
        /// </summary>
        public static string coinsLbl {
            get {
                return ResourceManager.GetString("coinsLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimes:.
        /// </summary>
        public static string dimesLbl {
            get {
                return ResourceManager.GetString("dimesLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifties:.
        /// </summary>
        public static string fiftLbl {
            get {
                return ResourceManager.GetString("fiftLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fives:.
        /// </summary>
        public static string fiveLbl {
            get {
                return ResourceManager.GetString("fiveLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hundreds:.
        /// </summary>
        public static string hundLbl {
            get {
                return ResourceManager.GetString("hundLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loonies:.
        /// </summary>
        public static string loonLbl {
            get {
                return ResourceManager.GetString("loonLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickels:.
        /// </summary>
        public static string nickelsLBL {
            get {
                return ResourceManager.GetString("nickelsLBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarters:.
        /// </summary>
        public static string qrtrsLbl {
            get {
                return ResourceManager.GetString("qrtrsLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string reportBtn {
            get {
                return ResourceManager.GetString("reportBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tens:.
        /// </summary>
        public static string tensLbl {
            get {
                return ResourceManager.GetString("tensLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toonies:.
        /// </summary>
        public static string toonLbl {
            get {
                return ResourceManager.GetString("toonLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string totalBtn {
            get {
                return ResourceManager.GetString("totalBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Bills.
        /// </summary>
        public static string totBillsBtn {
            get {
                return ResourceManager.GetString("totBillsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Coins.
        /// </summary>
        public static string totCoinsBtn {
            get {
                return ResourceManager.GetString("totCoinsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twenties:.
        /// </summary>
        public static string twenLbl {
            get {
                return ResourceManager.GetString("twenLbl", resourceCulture);
            }
        }
    }
}
